version: '2'
services:
  raspinloop-config-server:
    image: raspinloop/configuration
    environment:
      GIT_PASSWORD: <YOUR_GIT_PASSORD>
      GIT_URL: https://github.com/fmahiant/raspinloop-service-configs.git
      GIT_USER: raspinloopConfigReader
  raspinloop-redis:
    image: redis
  modelicamodelservice:
    image:  raspinloop/modelicamodelservice
    ports:
    - "8080:8080"    
  