server:
  port: 8888
  
spring:
    cloud:
      config:
        server:
          git:
            uri: ${GIT_URL}
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
                                   
logging:
    level:
        root: INFO                      
