/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.raspinloop.agent.launcherRunnerIpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ReportType implements org.apache.thrift.TEnum {
  Error(0),
  Info(1),
  Log(2),
  Trace(3);

  private final int value;

  private ReportType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReportType findByValue(int value) { 
    switch (value) {
      case 0:
        return Error;
      case 1:
        return Info;
      case 2:
        return Log;
      case 3:
        return Trace;
      default:
        return null;
    }
  }
}
